#ifndef __ihmc_psyonic_ros2__msg__AbilityHandCommand__idl__
#define __ihmc_psyonic_ros2__msg__AbilityHandCommand__idl__

module ihmc_psyonic_ros2
{
  module msg
  {
    module dds
    {
      const octet POSITION_CONTROL =
      0;

      const octet VELOCITY_CONTROL =
      1;

      const octet VEL_TO_POS_CONTROL =
      2;

      const octet GRIP_CONTROL =
      3;

      const octet POWER_GRIP =
      0;

      const octet KEY_GRIP =
      1;

      const octet TRIPOD_GRIP =
      2;

      const octet RELAX_GRIP =
      3;

      const octet RUDE_GRIP =
      4;


      @TypeCode(type="ihmc_psyonic_ros2::msg::dds_::AbilityHandCommand_")
      struct AbilityHandCommand
      {
        /**
         * The hand's serial number. E.g. 24ABH265
         */
        string<8> serial_number;
        /**
         * Specifies the control mode
         * Default = position control
         */
        octet control_mode;
        octet grip;
        float goal_positions[6];
        float goal_velocities[6];
      };
    };
  };
};

#endif
