#ifndef __ihmc_psyonic_ros2__msg__AbilityHandState__idl__
#define __ihmc_psyonic_ros2__msg__AbilityHandState__idl__

module ihmc_psyonic_ros2
{
  module msg
  {
    module dds
    {
      const octet LEFT =
      0;

      const octet RIGHT =
      1;


      @TypeCode(type="ihmc_psyonic_ros2::msg::dds_::AbilityHandState_")
      struct AbilityHandState
      {
        /**
         * The hand's serial number. E.g. 24ABH265
         */
        string<8> serial_number;
        /**
         * Specifies the side of the robot of the hand being referred to
         */
        @defaultValue(value=255)
        octet hand_side;
        /**
         * The actuator positions in degrees
         */
        float actuator_positions[6];
      };
    };
  };
};

#endif
